# Generated by Django 3.2.14 on 2022-07-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_aactive',
            new_name='is_active',
        ),
    ]
